In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('players.csv')

In [5]:
df

,full_school_name,school_name,player_name,position,height,weight,year,hometown,state,id
0,Cincinnati Bearcats,Cincinnati,Ralph Abernathy,RB,67.0,161.0,JR,"ATLANTA, GA",GA,1
1,Cincinnati Bearcats,Cincinnati,Mekale McKay,WR,78.0,195.0,SO,"LOUISVILLE, KY",KY,2
2,Cincinnati Bearcats,Cincinnati,Trenier Orr,CB,71.0,177.0,SO,"WINTER GARDEN, FL",FL,3
3,Cincinnati Bearcats,Cincinnati,Bennie Coney,QB,75.0,216.0,FR,"PLANT CITY, FL",FL,4
4,Cincinnati Bearcats,Cincinnati,Johnny Holton,WR,75.0,190.0,JR,"MIAMI, FL",FL,5
...,...,...,...,...,...,...,...,...,...,...
9995,San Jose State Spartans,San Jose State,Nate Velichko,OT,79.0,275.0,FR,"FOSTER CITY, CA",CA,9996
9996,San Jose State Spartans,San Jose State,Evan Sarver,OT,77.0,281.0,FR,"QUEEN CREEK, AZ",AZ,9997
9997,San Jose State Spartans,San Jose State,Oscar Barron,G,76.0,277.0,FR,"BUENA PARK, CA",CA,9998
9998,San Jose State Spartans,San Jose State,Jon Meyer,OT,77.0,275.0,SR,"SAN JOSE, CA",CA,9999
9999,San Jose State Spartans,San Jose State,Max Miller,TE,78.0,243.0,SR,"STUART, IA",IA,10000

In [6]:
df['state'].unique

<bound method Series.unique of 0       GA
1       KY
2       FL
3       FL
4       FL
        ..
9995    CA
9996    AZ
9997    CA
9998    CA
9999    IA
Name: state, Length: 10000, dtype: object>